### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by mmathieu90** [depilz/Solar2D-template#1]
Not sure if it's me or the template, as I'm totally newbie, but it's stuck on the loading screen. It says "Welcome" on purple background, and nothing else.

**Comment by depilz** [comment]
Sorry, I mistook you for someone I'm working with on another project (That's the reason for the previous answer haha)

Yes, this is just a template for you to build your games. The idea of this template is to keep everything organized and that the application is easily scalable.

If you are just starting with Solar2D, I suggest you to follow the (Solar2D tutorials)[https://coronalabs.com/learn/]

I apologize that there is still no README nor a proper guide for this template yet, but you can DM any question on Discord. My ID is depilz#0699

**Comment by depilz** [comment]
In the Environment file, you are supposed to add any evironment related stuff, so you can add all the physic objects (Ground, boxes) and in Story file you can add all the logical stuff for each level (world, cut-scene or whatever that has an encapsulated logic)

You also have a specific file to add all the UI stuff.

**Comment by mmathieu90** [comment]
I understand, I thought it was working as is. Thank you for your quick response. (should I close ?)

**Comment by depilz** [comment]
I hope you find it useful! 😄
